import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const read=async name=>(await readFile(new URL('./web/js/screens/'+name+'.js',import.meta.url),'utf8')).replace(/^import .*;$/gm,'');
function harness(){const nodes=new Map(),el=()=>({textContent:'',innerHTML:'',hidden:false,style:{},dataset:{},children:[],append(...x){this.children.push(...x);}});let screen;const env={budgetHelpHTML:"",currentScreen:()=>"budget",document:{getElementById:id=>{if(!nodes.has(id))nodes.set(id,el());return nodes.get(id);},createElement:el,createTextNode:x=>x},register:s=>screen=s,addStrings(){},T:k=>k,sub:(k,v)=>k+' '+Object.values(v).join(' / '),fmtFull:String,fmtDate:String,fmtMoney:String,fmtMonth:String,esc:String,icon:()=>'',setAction(){},mask:{},haptic:{},getJSON:async()=>{}};vm.createContext(env);return {env,nodes,get screen(){return screen;}};}
let h=harness();h.env.getJSON=async(_,cb)=>cb({loans:[{id:'a',name:'A',balance_major:10,currency:'AMD',balance_as_of:'2025-01-01'}]});vm.runInContext(await read('home'),h.env);await h.screen.onShow();assert.match(h.nodes.get('home-content').innerHTML,/2025-01-01/);assert.match(h.nodes.get('home-content').innerHTML,/<small[^>]*display:block[^>]*>[^<]*2025-01-01/,'Home balance date has its own line without extra padding');
h=harness();vm.runInContext(await read('loans'),h.env);const loans=[{id:'a',currency:'AMD',balance_major:10,balance_as_of:'2025-01-01',needs_reconciliation:true},{id:'b',currency:'AMD',balance_major:20,balance_as_of:'2026-02-02'}];h.env.summarise(loans);assert.match(h.nodes.get('m-asof').textContent,/2025-01-01 \/ 2026-02-02/);const card=h.env.loanCard(loans[0]);assert.match(card.children[1].children[0].textContent,/payment.review.*2025-01-01/);h.env.summarise([loans[0]]);assert.match(h.nodes.get('m-asof').textContent,/balance.asof/);h.env.summarise([{...loans[0],balance_as_of:null}]);assert.match(h.nodes.get('m-asof').textContent,/balance.partial/);
h=harness();vm.runInContext(await read('budget'),h.env);h.env.render({monthly_major:20,currency:'AMD',opening_major:0,opening_as_of:'2026-09-03'});let facts=h.nodes.get('bo-facts').children;assert.equal(facts.find(row=>row.children[0].textContent==='budget.opening').children[1].textContent,'0');assert.equal(facts.find(row=>row.children[0].textContent==='budget.cashdate').children[1].textContent,'2026-09-03');assert.equal(facts.find(row=>row.children[0].textContent==='budget.moneyMonthly').children[1].textContent,'budget.unset');
h=harness();vm.runInContext((await read('budget-funding')).replace(/^export /gm,''),h.env);vm.runInContext(await read('budget'),h.env);h.env.render({monthly_major:20,currency:'AMD',currency_exponent:2,funding:{monthly_minor:123456789},opening_major:0,opening_as_of:'2026-09-03'});assert.equal(h.nodes.get('bo-facts').children.find(row=>row.children[0].textContent==='budget.moneyMonthly').children[1].textContent,'AMD 1 234 567.89','declared funding is distinct from spending permission and retains exact cents');
h=harness();const calls=[];let report={proposal:'original + source',as_of:'2026-09-03',health:'unknown',base:{id:'base',status:'passed',reason:'exact_selected_policy_replay'},cases:[{id:'required_payment_increase',status:'unknown',reason:'required_adjustment_terms_unverified'}]};h.env.getJSON=async(path,cb)=>{calls.push(path);cb(report);};vm.runInContext(await read('plan-stress'),h.env);h.screen.onMount();await h.screen.onShow(null,{sheet:{proposal:report.proposal}});assert.equal(calls[0],'api/plan/stress?proposal=original%20%2B%20source');assert.match(h.nodes.get('stress-result').innerHTML,/stress.unknown/);assert.match(h.nodes.get('stress-result').innerHTML,/stress.required_adjustment_terms_unverified/);await h.nodes.get('stress-retry').onclick();assert.equal(calls[1],calls[0]);report={...report,proposal:'different'};await h.nodes.get('stress-retry').onclick();assert.equal(h.nodes.get('stress-error').textContent,'err.load');await h.screen.onShow(null,null);assert.equal(calls.length,3);assert.equal(h.nodes.get('stress-error').textContent,'stress.missing');
console.log('Balance dates, mixed-date summaries, explicit zero cash, exact stress source/retry and Unknown disclosure passed.');
