import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const source=(await readFile(new URL('./web/js/loan-mutations.js',import.meta.url),'utf8')).replace(/^import .*;$/gm,'').replaceAll('export ','');
const calls=[];let key=0;let reply=()=>{throw new TypeError('offline');};
const env={Map,Error,TypeError,JSON,String,crypto:{randomUUID:()=>`command-${++key}`},addStrings(){},T:x=>x,api:async(path,request)=>{calls.push({path,request});return reply();}};
vm.createContext(env);vm.runInContext(source,env);
await assert.rejects(env.loanMutation('api/loans','POST',{name:'Original'}),/offline/);
await assert.rejects(env.loanMutation('api/loans','POST',{name:'Changed'}),/loan_retry_pending/);
assert.equal(calls.length,1,'an uncertain command cannot be replaced with edited intent');
reply=()=>({ok:true,status:201});await env.loanMutation('api/loans','POST',{name:'Original'});
assert.equal(calls[0].request.headers['Idempotency-Key'],calls[1].request.headers['Idempotency-Key']);
await env.loanMutation('api/loans','POST',{name:'Another'});
assert.notEqual(calls[1].request.headers['Idempotency-Key'],calls[2].request.headers['Idempotency-Key']);
reply=()=>({ok:false,status:503});await env.loanMutation('api/loans/one','DELETE',undefined,7);
reply=()=>({ok:true,status:200});await env.loanMutation('api/loans/one','DELETE',undefined,7);
assert.equal(calls[3].request.headers['Idempotency-Key'],calls[4].request.headers['Idempotency-Key']);
assert.equal(calls[4].request.headers['If-Match'],'7');
reply=()=>({ok:false,status:409});await env.loanMutation('api/loans/one','PATCH',{name:'A'},8);
reply=()=>({ok:true,status:200});await env.loanMutation('api/loans/one','PATCH',{name:'B'},9);
assert.notEqual(calls[5].request.headers['Idempotency-Key'],calls[6].request.headers['Idempotency-Key']);
console.log('Loan retries preserve identity and payload; conflicts require a new reviewed command');
reply=()=>({ok:false,status:503});
await env.loanMutation('api/loans/two','PATCH',{name:'Original'},10);
const original=calls.at(-1).request;
reply=()=>({ok:true,status:200});
const button={};let recovered=false;
env.showLoanRetry(button,'api/loans/two',async()=>{recovered=true;});
assert.equal(button.hidden,false);
await button.onclick();
assert.equal(recovered,true);
assert.equal(calls.at(-1).request.body,original.body);
assert.equal(calls.at(-1).request.headers['Idempotency-Key'],original.headers['Idempotency-Key']);
assert.equal(calls.at(-1).request.headers['If-Match'],'10');
